"""
Pydantic models for RunLab
Defines the structure of runme.md specs, inputs, outputs, and UI configuration
"""
from typing import Optional, Literal, Any, Dict, List
from pydantic import BaseModel, Field


class InputField(BaseModel):
    """Definition of an input field from runme.md"""
    name: str
    type: Literal["string", "integer", "float", "boolean", "file"]
    description: Optional[str] = None
    required: bool = True
    default: Optional[Any] = None
    min: Optional[float] = None
    max: Optional[float] = None
    example: Optional[str] = None


class ComputeRequirements(BaseModel):
    """Compute resources needed for execution"""
    cpu: int = Field(default=2, ge=1, le=32)
    memory: str = Field(default="4GB")
    gpu: Optional[str] = Field(default=None, description="GPU type like 'T4', 'A10G', or 'none'")
    timeout: int = Field(default=300, ge=10, le=3600, description="Timeout in seconds")


class ContainerSpec(BaseModel):
    """Container configuration"""
    image: str = Field(default="python:3.11-slim")
    working_dir: str = Field(default="/app")


class OutputSpec(BaseModel):
    """Output configuration"""
    location: str = Field(default="/outputs")
    type: Literal["files", "stdout", "both"] = "files"
    mount_to_s3: bool = False


class RunmeSpec(BaseModel):
    """Complete parsed specification from runme.md"""
    name: str
    description: Optional[str] = None
    version: str = "1.0.0"
    container: ContainerSpec
    compute: ComputeRequirements
    inputs: List[InputField]
    command: str
    outputs: OutputSpec


class UIFieldConfig(BaseModel):
    """UI configuration for a single input field"""
    name: str
    type: Literal["text", "number", "checkbox", "file", "textarea"]
    label: str
    required: bool = True
    default: Optional[Any] = None
    min: Optional[float] = None
    max: Optional[float] = None
    placeholder: Optional[str] = None
    help_text: Optional[str] = None


class UIConfig(BaseModel):
    """Complete UI configuration generated by Claude"""
    title: str
    description: Optional[str] = None
    fields: List[UIFieldConfig]


class ParsedResult(BaseModel):
    """Result from parsing runme.md"""
    spec: RunmeSpec
    ui_config: UIConfig


class JobRequest(BaseModel):
    """Request to run a job"""
    spec_name: str
    inputs: Dict[str, Any]


class JobStatus(BaseModel):
    """Status of a running job"""
    job_id: str
    status: Literal["pending", "running", "completed", "failed"]
    created_at: str
    completed_at: Optional[str] = None
    error: Optional[str] = None
    output_urls: Optional[List[str]] = None
    logs: Optional[str] = None


class ParseRequest(BaseModel):
    """Request to parse a runme.md file"""
    content: str
    spec_name: Optional[str] = None
